# Generated by Django 4.1.4 on 2022-12-12 18:58

import django.core.validators
from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('status', models.CharField(blank=True, choices=[('STOCK', 'В наличии'), ('ORDER', 'Под заказ'), ('EXPECTED', 'Ожидается поступление'), ('OUT', 'Нет в наличии'), ('NOT PRODUCED', 'Не производится')], max_length=20, null=True, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[shop.validators.image_extension_validator], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
    ]
