# Generated by Django 4.1.4 on 2022-12-12 19:24

from django.db import migrations, models
import shop.models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.generate_path, validators=[shop.validators.image_extension_validator], verbose_name='Изображение'),
        ),
    ]
